import '~/styles/globals.css'

import { ThemeProvider } from '~/components/ThemeProvider'
import { CanNavigateBackContextProvider, SearchTermContextProvider } from '~/context'
import { TRPCReactProvider } from '~/trpc/react'

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <TRPCReactProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <SearchTermContextProvider>
              <CanNavigateBackContextProvider>{children}</CanNavigateBackContextProvider>
            </SearchTermContextProvider>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
